import axios from 'axios';

// Define the interface for an LLM configuration object
export interface LLMConfig {
  id: string; // Assuming the API returns an 'id' for existing configurations
  base_url: string;
  model: string;
  api_key: string;
}

// Define the interface for input when creating or updating a configuration
// 'id' is omitted as it's typically generated by the backend
export type LLMConfigInput = Omit<LLMConfig, 'id'>;

const API_BASE = `${import.meta.env.VITE_BACKEND_URL}/llm/llm_config`;

// Fetches all LLM configurations
export const getConfigs = () => axios.get<LLMConfig[]>(API_BASE);

// Creates a new LLM configuration
export const createConfig = (config: LLMConfigInput) => axios.post<LLMConfig>(API_BASE, config);

// Updates an existing LLM configuration by ID
export const updateConfig = (id: string, config: LLMConfigInput) => axios.patch<LLMConfig>(`${API_BASE}/${id}`, config);

// Deletes an LLM configuration by ID
export const deleteConfig = (id: string) => axios.delete<void>(`${API_BASE}/${id}`);
